# Generated by Django 4.2 on 2023-05-01 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'NPC'), (2, 'player class'), (3, 'loot'), (4, 'sound'), (5, 'project'), (6, 'doing'), (7, 'anti')])),
                ('bonus', models.PositiveSmallIntegerField(default=1)),
                ('buy_price', models.PositiveIntegerField(blank=True, null=True)),
                ('rent_price', models.PositiveIntegerField(blank=True, null=True)),
                ('sp_per_usage', models.SmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turn', models.PositiveSmallIntegerField(default=1)),
                ('turn_stage', models.PositiveSmallIntegerField(choices=[(1, 'first'), (2, 'decision'), (3, 'making sound'), (4, 'calculating income'), (5, 'free time after party')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.PositiveSmallIntegerField(default=1)),
                ('energy', models.PositiveSmallIntegerField(default=40)),
                ('bankroll', models.PositiveIntegerField(default=12000)),
                ('sp', models.PositiveSmallIntegerField(default=3)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'in hand'), (2, 'card at the table'), (3, 'card currently in deck')], default=3)),
                ('description', models.PositiveSmallIntegerField(choices=[(1, 'commonly'), (2, 'card in rent'), (3, "card in owner's hand")], default=1)),
                ('buy_price', models.PositiveIntegerField(blank=True, null=True)),
                ('rent_price', models.PositiveIntegerField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='game.card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_states', to='game.game')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_cards', to='game.player')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('cards', models.ManyToManyField(related_name='decks', to='game.card')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'owner')},
            },
        ),
    ]
