# Generated by Django 4.2 on 2023-05-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardstate',
            old_name='description',
            new_name='state_description',
        ),
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn_stage',
            field=models.PositiveSmallIntegerField(choices=[(0, 'created'), (1, 'first'), (2, 'decision'), (3, 'making sound'), (4, 'calculating income'), (5, 'free time after party')], default=0),
        ),
    ]
