# Generated by Django 4.2.1 on 2023-05-15 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_rename_description_cardstate_state_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardstate',
            name='location',
            field=models.PositiveSmallIntegerField(choices=[(1, 'In hand'), (2, 'At the table'), (3, 'In deck')], default=3),
        ),
        migrations.AddField(
            model_name='cardstate',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Common'), (2, 'Rented'), (3, 'Bought')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='cardstate',
            unique_together={('game', 'card')},
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('game', 'user')},
        ),
        migrations.RemoveField(
            model_name='cardstate',
            name='state',
        ),
        migrations.RemoveField(
            model_name='cardstate',
            name='state_description',
        ),
    ]
